name: xfads
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - filelock=3.13.1
  - freetype=2.12.1
  - fsspec=2024.3.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.3.0
  - openssl=3.0.13
  - pillow=10.3.0
  - pip=24.0
  - pycparser=2.21
  - python=3.10.14
  - pytorch=2.2.0
  - pytorch-cpu=2.2.0
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - sympy=1.12
  - tk=8.6.14
  - torchvision-cpu=0.2.2
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - einops==0.8.0
      - fonttools==4.52.4
      - frozenlist==1.4.1
      - hydra-core==1.3.2
      - idna==3.7
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - matplotlib==3.9.0
      - multidict==6.0.5
      - omegaconf==2.3.0
      - packaging==24.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.2.5
      - pyyaml==6.0.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - threadpoolctl==3.5.0
      - torchmetrics==1.4.0.post0
      - tqdm==4.66.4
      - xfads==0.5.0
      - yarl==1.9.4
