# --- graphical model --- #
n_latents: 2
n_latents_read: 2

rank_local: 2
rank_backward: 2

Q_init: 1e-1
n_hidden_dynamics: 64

# --- inference network --- #
n_samples: 5
n_hidden_local: 128
n_hidden_backward: 64

# --- hyperparameters --- #
use_cd: False
p_mask_a: 0.5
p_mask_b: 0.0
p_mask_apb: 0.0
p_mask_y_in: 0.0
p_local_dropout: 0.4
p_backward_dropout: 0.0

# --- training --- #
device: 'cpu'
data_device: 'cpu'

lr: 1e-3
n_epochs: 1500
batch_sz: 128

# --- misc --- #
bin_sz: 20e-3
bin_sz_ms: 20

seed: 1234
default_dtype: torch.float32

# --- ray --- #
n_ray_samples: 10


