n_latents: 40
n_latents_read: 30
rank_local: 1
rank_backward: 4
Q_init: 0.1
n_hidden_dynamics: 128
n_samples: 40
n_hidden_local: 512
n_hidden_backward: 128
use_cd: true
p_mask_a: 0.12012925434046595
p_mask_b: 0.032872955817357906
p_mask_apb: 0.08233141364362467
p_mask_y_in: 0.3
p_local_dropout: 0.5
p_backward_dropout: 0.0
device: cpu
data_device: cpu
lr: 0.001
n_epochs: 2
batch_sz: 128
bin_sz: 0.02
bin_sz_ms: 20
seed: 1234
default_dtype: torch.float32
n_ray_samples: 10
