# --- graphical model --- #
n_latents: 40
n_latents_read: 30

rank_local: 10
rank_backward: 5

Q_init: 1e-1
n_hidden_dynamics: 128

# --- inference network --- #
n_samples: 40
n_hidden_local: 512
n_hidden_backward: 128

# --- hyperparameters --- #
use_cd: True
p_mask_a: 0.25
p_mask_b: 0.1
p_mask_apb: 0.1
p_mask_y_in: 0.0
p_local_dropout: 0.5
p_backward_dropout: 0.0

# --- training --- #
device: 'cpu'
data_device: 'cpu'

lr: 1e-3
n_epochs: 2
batch_sz: 128

# --- misc --- #
bin_sz: 20e-3
bin_sz_ms: 20

seed: 1234
default_dtype: torch.float32

# --- ray --- #
n_ray_samples: 10


