# --- graphical model --- #
n_latents: 4
n_latents_read: 4

rank_local: 4   # original 4/4 -> 3/2 -> 2/1
rank_backward: 4

Q_init: 1e-1
n_hidden_dynamics: 64

# --- inference network --- #
n_samples: 25
n_hidden_local: 128
n_hidden_backward: 64 # 64 except for dvbf@128

# --- hyperparameters --- #
use_cd: False
p_mask_a: 0.0
p_mask_a_offset: 0.0
p_mask_b: 0.0
p_mask_b_offset: 0.0
p_mask_apb: 0.0
p_mask_y_in: 0.0
p_local_dropout: 0.4
p_backward_dropout: 0.0

# --- training --- #
device: 'cuda'
data_device: 'cuda'

lr: 1e-3
n_epochs: 2_000
batch_sz: 256
check_val_every_n_epoch: 50

# --- misc --- #
bin_sz: 20e-3
bin_sz_ms: 20

seed: 1236
default_dtype: torch.float32

# --- ray --- #
n_ray_samples: 10


