name: xfads
channels:
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - comm=0.1.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - fsspec=2024.3.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - jedi=0.18.1
  - jinja2=3.1.3
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libuv=1.44.2
  - llvm-openmp=14.0.6
  - matplotlib-inline=0.1.6
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.13
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - python=3.9.19
  - pytorch=2.2.0
  - pytorch-cpu=2.2.0
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - tzdata=2024a
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - einops==0.8.0
      - filelock==3.14.0
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - hydra-core==1.3.2
      - idna==3.7
      - importlib-resources==6.4.0
      - joblib==1.4.0
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - multidict==6.0.5
      - networkx==3.2.1
      - omegaconf==2.3.0
      - packaging==24.0
      - pillow==10.3.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.2.3
      - pyyaml==6.0.1
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - threadpoolctl==3.5.0
      - torchmetrics==1.3.2
      - tqdm==4.66.2
      - typing-extensions==4.11.0
      - yarl==1.9.4
      - zipp==3.18.1
